"""Initial schema

Revision ID: 7836ae2bb0b3
Revises: 
Create Date: 2026-08-06 19:54:57.276904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7836ae2bb0b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('conversation_type', sa.Enum('private', 'group', name='conversationtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("\n            (conversation_type = 'private' AND name IS NULL)\n            OR\n            (conversation_type = 'group' AND name IS NOT NULL)\n            ", name='ck_conversation_name_matches_type'),
    sa.CheckConstraint("conversation_type IN ('private', 'group')", name='ck_conversations_conversation_type_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('lock_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.Enum('active', 'deleted', 'blocked', name='userstatus'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'deleted', 'blocked')", name='ck_users_status_valid'),
    sa.CheckConstraint('failed_attempts BETWEEN 0 AND 20', name='ck_users_failed_attempts_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('conversation_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.Enum('active', 'left', 'removed', name='conversationmemberstatus'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='conversationmemberrole'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'member')", name='ck_conversation_members_role_valid'),
    sa.CheckConstraint("status IN ('active', 'left', 'removed')", name='ck_conversation_members_status_valid'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'conversation_id')
    )
    op.create_table('friend_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'canceled', name='friendrequeststatus'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'rejected', 'canceled')", name='ck_friend_requests_status_valid'),
    sa.CheckConstraint('sender_id <> receiver_id', name='ck_friend_requests_not_self'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.Enum('active', 'removed', name='friendstatus'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'removed')", name='ck_friends_status_valid'),
    sa.CheckConstraint('user_id < friend_id', name='ck_friends_user_id_less_than_friend_id'),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=10000), nullable=False),
    sa.Column('status', sa.Enum('active', 'deleted', name='messagestatus'), nullable=False),
    sa.Column('delivery_status', sa.Enum('sent', 'delivered', 'read', name='messagedeliverystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("delivery_status IN ('sent', 'delivered', 'read')", name='ck_messages_delivery_status_valid'),
    sa.CheckConstraint("status IN ('active', 'deleted')", name='ck_messages_status_valid'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('friends')
    op.drop_table('friend_requests')
    op.drop_table('conversation_members')
    op.drop_table('users')
    op.drop_table('conversations')
    # ### end Alembic commands ###
