"""changed 'deleted_for_user' to 'is_hidden'

Revision ID: 9df7b29f1968
Revises: a3c4b8309039
Create Date: 2026-08-01 21:45:03.194492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df7b29f1968'
down_revision: Union[str, Sequence[str], None] = 'a3c4b8309039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_members', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    op.drop_column('conversation_members', 'deleted_for_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_members', sa.Column('deleted_for_user', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('conversation_members', 'is_hidden')
    # ### end Alembic commands ###
